# Generated by Django 4.1.5 on 2023-01-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256)),
                ('subtitulo', models.CharField(max_length=1000)),
                ('cuerpo', models.CharField(max_length=1000, null=True)),
                ('fecha_publicacion', models.DateField(null=True)),
                ('autor', models.CharField(max_length=64)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias')),
            ],
        ),
    ]
