# Generated by Django 4.1.5 on 2023-02-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_blog', '0003_noticias_imagen_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='imagen_texto',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
